### ISSUE TITLE
Error with the latest GSAP - TimelineMax

### ISSUE THREAD

**Issue by deepsoul** [StephanGerbeth/agency-boilerplate#7]
There is an error with the latest GSAP-Package (1.18.6). When downgrade to 1.18.5, everything works fine

**Comment by ThornWalli** [comment]
No problem with GSAP, invalid import.

Fix 72723d5f276c61898476ef0c106089ef395b5535

**Comment by deepsoul** [comment]
check this: https://github.com/greensock/GreenSock-JS/issues/165
